# Generated by Django 5.0.6 on 2024-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
