# Generated by Django 5.0.6 on 2024-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
