# Generated by Django 5.0.6 on 2024-06-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_alter_translation_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='translation',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.translationkeys'),
        ),
    ]
