# Generated by Django 5.0.6 on 2024-06-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_rename_translationkeys_translationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationkey',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
