# Generated by Django 5.0.6 on 2024-06-26 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translation', '0005_rename_translationkeys_translationkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=32, unique=True)),
                ('selectedLang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.language')),
            ],
        ),
    ]
