# Generated by Django 5.0.6 on 2024-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedlanguage',
            name='sessionId',
            field=models.CharField(max_length=32),
        ),
    ]
