# Generated by Django 5.0.6 on 2024-06-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_selectedlanguage_sessionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedlanguage',
            old_name='sessionId',
            new_name='session',
        ),
    ]
