# Generated by Django 5.0.6 on 2024-06-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_rename_translationkeys_translationkey'),
        ('user', '0003_rename_sessionid_selectedlanguage_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='translation.language')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedLanguage',
        ),
    ]
