# Generated by Django 5.0.6 on 2024-07-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_langsession_delete_selectedlanguage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userInfo', models.CharField(max_length=100)),
                ('fb_url', models.URLField()),
                ('tw_url', models.URLField()),
                ('gg_url', models.URLField()),
                ('ln_url', models.URLField()),
                ('pi_url', models.URLField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
