# Generated by Django 5.0.6 on 2024-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='fb_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gg_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ln_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='pi_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='tw_url',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='userInfo',
            field=models.TextField(max_length=300),
        ),
    ]
