# Generated by Django 5.0.6 on 2024-07-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='fb_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gg_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='ln_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='pi_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='tw_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
