# Generated by Django 5.0.6 on 2024-07-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userdetail_fb_url_alter_userdetail_gg_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('requestHeaders', models.TextField()),
                ('responseHeaders', models.TextField()),
                ('getParams', models.TextField(blank=True, null=True)),
                ('postData', models.TextField(blank=True, null=True)),
                ('senderIP', models.GenericIPAddressField()),
                ('userAgent', models.CharField(max_length=255)),
                ('statusCode', models.IntegerField()),
                ('responseContent', models.TextField()),
                ('responseTime', models.FloatField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
