# Generated by Django 5.0.6 on 2024-07-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='userInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
